server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: kuenda-marketplace-backend
  datasource:
    url: jdbc:h2:mem:kuendadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Configurações de CORS permitidas para comunicação com o Frontend Vite
app:
  jwt:
    secret: "KuendaMarketplaceSuperSecretKey2026AngolaVerySecureForJwtSigning!"
    expiration-ms: 86400000 # 24 horas em milissegundos
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
      - "http://localhost:5173"
      - "https://*.run.app"

